version: "3.8"

services:
    nats:
        image: nats:latest
        command: []
        ports:
            - "4222:4222"
            - "6222:6222"
            - "8222:8222"
    authorization-service:
        image: jwalab/authorization-service:0.0.2
        ports:
            - "8999:8999"
    airlock:
        image: jwalab/airlock:0.0.7
        environment:
            - NATS_URL=nats://nats:4222
            - AUTH_URL=authorization-service:8999
            - AUTH_PROTOCOL=http
            - SECURE=false
        ports:
            - "8000:8000"
        depends_on:
            - "nats"
