#! /usr/bin/env bash

set -euo pipefail

export NATS_URL=nats://localhost:4222
export TOKEN_ENDPOINT=https://playtix.okta.com/oauth2/default/v1/token
export USERINFO_ENDPOINT=https://playtix.okta.com/oauth2/default/v1/userinfo
export AUTHORIZE_ENDPOINT=https://playtix.okta.com/oauth2/default/v1/authorize
export AUTHN_ENDPOINT=https://playtix.okta.com/api/v1/authn
export SESSIONS_ENDPOINT=https://playtix.okta.com/api/v1/sessions

declare -a tags=(
    $(git rev-parse --verify HEAD --short)
    $(node -p -e "require('./package.json').version")
)

declare name=$(node -p -e "require('./package.json').name")

function start() {
    docker-compose up
}

function stop() {
    docker-compose stop
}

function docker-build() {
    docker build . -t jwalab/$name
}

function docker-tag() {
    for tag in ${tags[@]}
    do
        docker tag jwalab/$name jwalab/$name:$tag
    done
}

function docker-push() {
    docker push jwalab/$name
    for tag in ${tags[@]}
    do
        docker push jwalab/$name:$tag
    done
}

function start-node() {
    node dist/index.js
}

function dev() {
    npm run dev
}

function build() {
    npm run build
}

function test() {
    npm run test
}

"$@"