version: 2.1
orbs:
    node: circleci/node@4.7.0
jobs:
    lint:
        executor: node/default
        steps:
            - checkout
            - run: npm ci
            - run: npm run lint
    test:
        machine:
            image: ubuntu-2004:202107-02
        steps:
            - checkout
            - run: nvm alias default 14.12.0
            - run:
                  command: docker-compose up
                  background: true
            - run: npm ci
            - run: npm run build
            - run:
                  command: ./run start-node
                  background: true
            - run: sleep 6
            - run: ./run test
workflows:
    tests:
        jobs:
            - lint
            - test
